### ISSUE TITLE
filter by date

### ISSUE THREAD

**Issue by melissaceleste** [melissaceleste/capstone-project#12]
As a user i want to filter the cards by purchase date

### Description
Klamotten die du in diesem Zeitraum gekauft hast: 

### Acceptance criteria

- [x] the app got a filter for purchase date of clothings
- [x] cards where show, which are bought in the selected time period

### Tasks

- [x] make a new branch
- [x] input field - type date
- [x] filter function
- [x] test

### Complexity
medium
