### ISSUE TITLE
filter by price

### ISSUE THREAD

**Issue by melissaceleste** [melissaceleste/capstone-project#13]
As a user i want to filter the cards by the price, i bought my clothings

### Description
Zeig mir Kleidung die weniger als <input> gekostet haben: 
Zeig mir Kleidung die mehr als <input> gekostet haben: 

oder preis: ___ (min) - ___ (max) (wie im Onlineshop)

### Acceptance criteria

- [x] the app got a filter for the price of clothings
- [x] cards where show, which are inside of the price range

### Tasks

- [x] make a new branch
- [x] input field 
- [x] filter function
- [x] test

### Complexity
medium
