### ISSUE TITLE
filter by clothingtype

### ISSUE THREAD

**Issue by melissaceleste** [melissaceleste/capstone-project#14]
As a user i want to filter the cards by the the clothingType

### Description

Dropdown with the options of clothing-types

### Acceptance criteria

- [x] the app got a filter for the clothingtype
- [x] show filtered cards
### Tasks

- [x] make a new branch
- [x] input field 
- [x] filter function
- [x] test

### Complexity
medium
