### ISSUE TITLE
layout - navigation over the clothing types

### ISSUE THREAD

**Issue by melissaceleste** [melissaceleste/capstone-project#15]
As a user i want to see a pretty layout of the second page, with clickable images for the clothing types

### Description

![Bildschirmfoto 2021-03-15 um 16 08 35 (2)](https://user-images.githubusercontent.com/77294948/111176065-4c3d8700-85a9-11eb-8605-634381e01e68.png)

--> "show all button" 

### Acceptance criteria

- [ ] the user can click on the clothing type, which shows a filtered overview (in another page) of the clicked clothing types
- [ ] show all button, which show all clothings randomly without sorting of clothing types (in another page)
- [ ] in the overview-page i can filter for price, name, store, date
- [ ] you can click on a return button, and come back to the clothing-type-page

### Tasks

- [x] make a new branch
- [ ] add the images for the buttons - in router?
- [ ] add "show all"
- [ ] pages of the selected clothing types
- [ ] return button
- [ ] insert filter functions
- [ ] test

### Complexity
high

**Comment by melissaceleste** [comment]
As a user i want to see a pretty layout of the second page, with clickable images for the clothing types

### Description

![Bildschirmfoto 2021-03-15 um 16 08 35 (2)](https://user-images.githubusercontent.com/77294948/111176065-4c3d8700-85a9-11eb-8605-634381e01e68.png)

--> "show all button" 


### Acceptance criteria

- [ ] the user can click on the clothing type, which shows a filtered overview (in another page) of the clicked clothing types
- [ ] show all button, which show all clothings randomly without sorting of clothing types (in another page)
- [ ] in the overview-page i can filter for price, name, store, date
- [ ] you can click on a return button, and come back to the clothing-type-page

### Tasks

- [x] make a new branch
- [ ] add the images for the buttons - in router?
- [ ] add "show all"
- [ ] pages of the selected clothing types
- [ ] return button
- [ ] insert filter functions
- [ ] test

### Complexity
high
