### ISSUE TITLE
delete seperate cards

### ISSUE THREAD

**Issue by melissaceleste** [melissaceleste/capstone-project#17]
As a user i want to delete seperate cards 

### Description
Delete-Button on the right upper corner of every card 

### Acceptance criteria

- [x] each (default-)card got a delete button
- [x] by clicking the button, the card is removed from all pages and local storage

### Tasks

- [x] make a new branch
- [x] adding uuid
- [x] input field 
- [x] filter function
- [x] test

### Complexity
medium
