### ISSUE TITLE
swipe function/ randomizer cards

### ISSUE THREAD

**Issue by melissaceleste** [melissaceleste/capstone-project#18]
As a user i want to see random cards of my clothes  on the homepage

### Description
![Bildschirmfoto 2021-03-21 um 19 49 05](https://user-images.githubusercontent.com/77294948/111917242-43ecbc80-8a7f-11eb-85fc-df4f85138045.png)

### Acceptance criteria

- [ ] the homepage shows random cards
- [ ] the cards are stacked
- [ ] you can swipe the upper card away to show the underneath card
- [ ] by clicking a button, all the cards (including the swiped cards) are mixed and presented again
### Tasks

- [ ] make a new branch
- [ ] <button> 
- [ ] random function
- [ ] swiping function and design
- [ ] test

### Complexity
high
