### ISSUE TITLE
Cards

### ISSUE THREAD

**Issue by melissaceleste** [melissaceleste/capstone-project#2]
As a user i want to see random cards with clothes

### Description
![Bildschirmfoto 2021-03-05 um 14 40 08 (2)](https://user-images.githubusercontent.com/77294948/110123400-1fc38700-7dc1-11eb-94b0-808b94e2e681.png)

### Acceptance criteria

- [x] the card got one picture of a clothing
- [x] the card got the name of the cloting

### Tasks

- [x] add static JSON-API with image and name
- [x] add a card component
- [x] fetch name and image from JSON to card component
- [x] add styling
- [x] Test on mobile and desktop

### Complexity

medium

**Comment by melissaceleste** [comment]
As a user i want to see random cards with clothes

### Description
![Bildschirmfoto 2021-03-05 um 14 40 08 (2)](https://user-images.githubusercontent.com/77294948/110123400-1fc38700-7dc1-11eb-94b0-808b94e2e681.png)

### Acceptance criteria

- [ ] the card got one picture of a clothing
- [ ] the card got the name of the cloting

### Tasks

- [ ] add static JSON-API with image and name
- [ ] add a card component
- [ ] fetch name and image from JSON to card component
- [ ] add styling
- [ ] Test on mobile and desktop

### Complexity

medium
