### ISSUE TITLE
add new card

### ISSUE THREAD

**Issue by melissaceleste** [melissaceleste/capstone-project#7]
As a user i want to add a new card, with a picture of my own clothes. 
I want to upload from my fotoalbum or directly take a picture with the camera

### Description

<img width="937" alt="Bildschirmfoto 2021-03-08 um 19 20 06" src="https://user-images.githubusercontent.com/77294948/110365196-0599db00-8045-11eb-9a93-ce7187ee14c0.png">

### Acceptance criteria

- [x] the user can upload a picture
- [x] add information to the picture 
- [x] safe it to the local storage

### Tasks

- [x] make a new branch
- [x] form (with further information)
- [ ] make all to lower case, so the user can write in uppercase but it's saved in lowercase
- [x] upload input (<input type="file value="upload"/>
- [x] local storage
- [x] button (add)
- [ ] tests
- [x] storybook
- [ ] PR
### Complexity
high
