### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by melissaceleste** [melissaceleste/capstone-project#9]
As a user i want to change the pages by clicking on the navbar

### Description

Navigation-bar with 3 nav-links:
home | Kleiderschrank | neu

### Acceptance criteria

- [x] the user can change the pages by cklicking
- [x] the path is shown

### Tasks

- [x] make a new branch
- [x] import NavLink from react-router-dom
- [x] add <Nav> in App.js
- [x] make 3 page-components
- [x] fill the page-components
- [x] make 3 buttons for the navigation
- [x] add NavLink-Prop to the buttons
- [x] design
- [x] testing
- [ ] PR

### Complexity
high
